platform :ios, '15.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end


post_install do |installer|
  team_id = ENV['TEAM_ID'] || 'BYQUNNQSQH'
  bundle_id = ENV['BUNDLE_ID'] || 'com.saoirse.epi'

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|

      # 1) Remove signing from all pods by default
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGN_IDENTITY')
      config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      config.build_settings.delete('DEVELOPMENT_TEAM')

      # 2) Enable signing ONLY for privacy pods + resources + Pods-Runner + Runner
      if target.name.downcase.include?("privacy") ||
         target.name.end_with?("-Resources") ||
         target.name.end_with?("_Resources") ||
         target.name == "Pods-Runner" ||
         target.name == "Runner"

        config.build_settings['DEVELOPMENT_TEAM'] = team_id
        config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
        config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Distribution'
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = "match AppStore #{bundle_id}"
      end

      # 3) Required Xcode 16 / Firebase build settings
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
      config.build_settings['DEAD_CODE_STRIPPING'] = 'NO'
      config.build_settings['TAPI_VERIFY_MODE'] = 'ErrorsOnly'
      config.build_settings['LD_GENERATE_MAP_FILE'] = 'NO'
      config.build_settings['DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC'] = 'YES'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'

      # 4) Enforce minimum iOS 12.0 deployment target
      current = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']

      begin
        needs_update = current.nil? || current.to_f < 12.0
      rescue
        needs_update = true
      end

      if needs_update
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end

    end
  end
end
