app_identifier("com.saoirse.epi")
platform("ios")

# Binary already uploaded via pilot
skip_binary_upload(true)

# Upload metadata from folder
skip_metadata(false)
skip_screenshots(true)

run_precheck_before_submit(false)

submit_for_review(true)
automatic_release(false)

submission_information({
  export_compliance_uses_encryption: false
})
